language: java
sudo: false

before_install:
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - "hiptest-publisher -c cucumber-java.conf --only=features,step_definitions --test-run-id=163883"

script:
  - mvn test

after_script:
  - hiptest-publisher -c cucumber-java.conf --push=target/cuke-results-junit.xml --test-run-id=163883
